// frontend/admin/react/src/core/preferences/components/PreferencesPanel/LayoutPanel.tsx
import React from 'react';
import {Button, Input, InputNumber, Segmented, Select, Space, Switch} from 'antd';
import {MinusOutlined, PlusOutlined, QuestionCircleOutlined} from '@ant-design/icons';
import { useDynamicI18n } from '@/core/i18n';
import {usePreferencesStore} from '../../store';
import type {ContentCompactType, LayoutType} from '../../types';
import './LayoutPanel.style.less';

/** 布局选项 */
const LAYOUT_OPTIONS = [
  {
    label: 'layout.modes.sidebarNav',
    value: 'sidebar-nav',
    icon: '📋',
  },
  {
    label: 'layout.modes.sidebarMixedNav',
    value: 'sidebar-mixed-nav',
    icon: '📑',
  },
  {
    label: 'layout.modes.headerNav',
    value: 'header-nav',
    icon: '',
  },
  {
    label: 'layout.modes.mixedNav',
    value: 'mixed-nav',
    icon: '📊',
  },
  {
    label: 'layout.modes.fullContent',
    value: 'full-content',
    icon: '📱',
  },
];

/** 内容宽度选项 */
const CONTENT_COMPACT_OPTIONS = [
  { label: 'layout.contentModes.wide', value: 'wide' },
  { label: 'layout.contentModes.compact', value: 'compact' },
];

export const LayoutPanel: React.FC = () => {
  const { preferences, setPreferences } = usePreferencesStore();
  const { t } = useDynamicI18n({ namespace: 'preferences' });

  const handleLayoutChange = (layout: LayoutType) => {
    setPreferences({ app: { layout } });
  };

  const handleContentCompactChange = (compact: ContentCompactType) => {
    setPreferences({ app: { contentCompact: compact } });
  };

  const handleSidebarWidthChange = (width: number | null) => {
    if (width && width >= 180 && width <= 320) {
      setPreferences({ sidebar: { width } });
    }
  };

  return (
    <div className="layout-panel">
      {/* 布局选择 */}
      <section className="layout-section">
        <h3 className="section-title">布局</h3>
        <div className="layout-grid">
          {LAYOUT_OPTIONS.map((option) => (
            <div
              key={option.value}
              className={`layout-item ${preferences.app.layout === option.value ? 'active' : ''}`}
              onClick={() => handleLayoutChange(option.value as LayoutType)}
            >
              <div className="layout-preview">
                {/* 渲染真实的布局示意图 */}
                {option.value === 'sidebar-nav' && (
                  <div className="layout-visual sidebar-nav">
                    <div className="sidebar" />
                    <div className="main-content">
                      <div className="header-bar gray" />
                      <div className="content-area">
                        <div className="block-row">
                          <div className="block" />
                          <div className="block" />
                        </div>
                        <div className="block" />
                      </div>
                    </div>
                  </div>
                )}
                {option.value === 'sidebar-mixed-nav' && (
                  <div className="layout-visual sidebar-mixed-nav">
                    <div className="sidebar thin primary" />
                    <div className="sidebar thin gray" />
                    <div className="main-content">
                      <div className="header-bar gray" />
                      <div className="content-area">
                        <div className="block-row">
                          <div className="block" />
                          <div className="block" />
                        </div>
                        <div className="block" />
                      </div>
                    </div>
                  </div>
                )}
                {option.value === 'header-nav' && (
                  <div className="layout-visual header-nav">
                    <div className="content-wrapper">
                      <div className="header-bar full-width">
                        <div className="menu-item" />
                        <div className="menu-item" />
                        <div className="menu-item" />
                        <div className="menu-item" />
                        <div className="menu-item" />
                      </div>
                      <div className="content-area">
                        <div className="block-row">
                          <div className="block" />
                          <div className="block" />
                        </div>
                        <div className="block" />
                      </div>
                    </div>
                  </div>
                )}
                {option.value === 'mixed-nav' && (
                  <div className="layout-visual mixed-nav">
                    <div className="content-wrapper">
                      <div className="header-bar full-width">
                        <div className="menu-item" />
                        <div className="menu-item" />
                        <div className="menu-item" />
                      </div>
                      <div className="main-content">
                        <div className="sidebar thin gray" />
                        <div className="content-area">
                          <div className="block-row">
                            <div className="block" />
                            <div className="block" />
                          </div>
                          <div className="block" />
                        </div>
                      </div>
                    </div>
                  </div>
                )}
                {option.value === 'full-content' && (
                  <div className="layout-visual full-content">
                    <div className="content-area full-width">
                      <div className="block-row">
                        <div className="block" />
                        <div className="block" />
                      </div>
                      <div className="block" />
                    </div>
                  </div>
                )}
              </div>
              <div className="layout-label">
                <span>{t(option.label)}</span>
                <QuestionCircleOutlined className="help-icon" />
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 内容宽度 */}
      <section className="layout-section">
        <h3 className="section-title">内容</h3>
        <div className="content-compact-grid">
          {CONTENT_COMPACT_OPTIONS.map((option) => (
            <div
              key={option.value}
              className={`content-compact-item ${preferences.app.contentCompact === option.value ? 'active' : ''}`}
              onClick={() => handleContentCompactChange(option.value as ContentCompactType)}
            >
              <div className="content-preview">
                <div className={`preview-bar ${option.value === 'compact' ? 'narrow' : 'wide'}`} />
              </div>
              <span>{t(option.label)}</span>
            </div>
          ))}
        </div>
      </section>

      {/* 侧边栏设置 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.sidebar')}</h3>
        <div className="preference-item">
          <span>{t('layout.showSidebar')}</span>
          <Switch
            checked={preferences.sidebar.enable}
            onChange={(checked) => setPreferences({ sidebar: { enable: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.collapseMenu')}</span>
          <Switch
            checked={preferences.sidebar.collapsed}
            onChange={(checked) => setPreferences({ sidebar: { collapsed: checked } })}
          />
        </div>
        <div className={`preference-item ${preferences.sidebar.collapsed ? 'disabled' : ''}`}>
          <span>{t('layout.collapseShowTitle')}</span>
          <Switch
            disabled={!preferences.sidebar.collapsed}
            checked={preferences.sidebar.collapsedShowTitle}
            onChange={(checked) => setPreferences({ sidebar: { collapsedShowTitle: checked } })}
          />
        </div>
        <div className="preference-item width-control">
          <span>{t('layout.width')}</span>
          <Space size={4}>
            <Button
              size="small"
              icon={<MinusOutlined/>}
              onClick={() => handleSidebarWidthChange(preferences.sidebar.width - 8)}
              disabled={preferences.sidebar.width <= 180}
            />
            <InputNumber
              min={180}
              max={320}
              value={preferences.sidebar.width}
              onChange={handleSidebarWidthChange}
              style={{width: 70}}  // 从80压缩到70
            />
            <Button
              size="small"
              icon={<PlusOutlined/>}
              onClick={() => handleSidebarWidthChange(preferences.sidebar.width + 8)}
              disabled={preferences.sidebar.width >= 320}
            />
          </Space>
        </div>
      </section>

      {/* 顶栏设置 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.header')}</h3>
        <div className="preference-item">
          <span>{t('layout.showHeader')}</span>
          <Switch
            checked={preferences.header.enable}
            onChange={(checked) => setPreferences({ header: { enable: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.mode')}</span>
          <Segmented
            options={[
              { label: t('layout.headerModes.fixed'), value: 'fixed' },
              { label: t('layout.headerModes.auto'), value: 'auto' },
              { label: t('layout.headerModes.static'), value: 'static' },
            ]}
            value={preferences.header.mode}
            onChange={(value) => setPreferences({ header: { mode: value as any } })}
          />
        </div>
      </section>

      {/* 导航菜单 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.navigationMenu')}</h3>
        <div className="preference-item">
          <span>{t('layout.menuStyle')}</span>
          <Segmented
            options={[
              { label: t('layout.menuStyles.rounded'), value: 'rounded' },
              { label: t('layout.menuStyles.plain'), value: 'plain' },
            ]}
            value={preferences.navigation.styleType}
            onChange={(value) => setPreferences({ navigation: { styleType: value as any } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.menuSplit')}</span>
          <Switch
            checked={preferences.navigation.split}
            onChange={(checked) => setPreferences({ navigation: { split: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.accordionMode')}</span>
          <Switch
            checked={preferences.navigation.accordion}
            onChange={(checked) => setPreferences({ navigation: { accordion: checked } })}
          />
        </div>
      </section>

      {/* 面包屑导航 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.breadcrumb')}</h3>
        <div className="preference-item">
          <span>{t('layout.enableBreadcrumb')}</span>
          <Switch
            checked={preferences.breadcrumb.enable}
            onChange={(checked) => setPreferences({ breadcrumb: { enable: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.hideWhenOnlyOne')}</span>
          <Switch
            checked={preferences.breadcrumb.hideOnlyOne}
            onChange={(checked) => setPreferences({ breadcrumb: { hideOnlyOne: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.showIcon')}</span>
          <Switch
            checked={preferences.breadcrumb.showIcon}
            onChange={(checked) => setPreferences({ breadcrumb: { showIcon: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.showHomeButton')}</span>
          <Switch
            checked={preferences.breadcrumb.showHome}
            onChange={(checked) => setPreferences({ breadcrumb: { showHome: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.breadcrumbStyle')}</span>
          <Segmented
            options={[
              { label: t('layout.breadcrumbStyles.normal'), value: 'normal' },
              { label: t('layout.breadcrumbStyles.background'), value: 'background' },
            ]}
            value={preferences.breadcrumb.styleType}
            onChange={(value) => setPreferences({ breadcrumb: { styleType: value as any } })}
          />
        </div>
      </section>

      {/* 标签栏 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.tabbar')}</h3>
        <div className="preference-item">
          <span>{t('layout.enableTabbar')}</span>
          <Switch
            checked={preferences.tabbar.enable}
            onChange={(checked) => setPreferences({ tabbar: { enable: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.persistTabs')}</span>
          <Switch
            checked={preferences.tabbar.persist}
            onChange={(checked) => setPreferences({ tabbar: { persist: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.draggableSort')}</span>
          <Switch
            checked={preferences.tabbar.draggable}
            onChange={(checked) => setPreferences({ tabbar: { draggable: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.showTabbarIcon')}</span>
          <Switch
            checked={preferences.tabbar.showIcon}
            onChange={(checked) => setPreferences({ tabbar: { showIcon: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.showMoreButton')}</span>
          <Switch
            checked={preferences.tabbar.showMore}
            onChange={(checked) => setPreferences({ tabbar: { showMore: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.showMaximizeButton')}</span>
          <Switch
            checked={preferences.tabbar.showMaximize}
            onChange={(checked) => setPreferences({ tabbar: { showMaximize: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.tabbarStyle')}</span>
          <Segmented
            options={[
              { label: t('layout.tabbarStyles.chrome'), value: 'chrome' },
              { label: t('layout.tabbarStyles.card'), value: 'card' },
              { label: t('layout.tabbarStyles.minimal'), value: 'minimal' },
            ]}
            value={preferences.tabbar.styleType}
            onChange={(value) => setPreferences({ tabbar: { styleType: value as any } })}
          />
        </div>
      </section>

      {/* 小部件 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.widgets')}</h3>
        <div className="preference-item">
          <span>{t('layout.globalSearch')}</span>
          <Switch
            checked={preferences.widget.globalSearch}
            onChange={(checked) => setPreferences({ widget: { globalSearch: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.themeToggle')}</span>
          <Switch
            checked={preferences.widget.themeToggle}
            onChange={(checked) => setPreferences({ widget: { themeToggle: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.languageToggle')}</span>
          <Switch
            checked={preferences.widget.languageToggle}
            onChange={(checked) => setPreferences({ widget: { languageToggle: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.fullscreen')}</span>
          <Switch
            checked={preferences.widget.fullscreen}
            onChange={(checked) => setPreferences({ widget: { fullscreen: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.notification')}</span>
          <Switch
            checked={preferences.widget.notification}
            onChange={(checked) => setPreferences({ widget: { notification: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.lockScreen')}</span>
          <Switch
            checked={preferences.widget.lockScreen}
            onChange={(checked) => setPreferences({ widget: { lockScreen: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.sidebarToggle')}</span>
          <Switch
            checked={preferences.widget.sidebarToggle}
            onChange={(checked) => setPreferences({ widget: { sidebarToggle: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.refresh')}</span>
          <Switch
            checked={preferences.widget.refresh}
            onChange={(checked) => setPreferences({ widget: { refresh: checked } })}
          />
        </div>
        <div className="preference-item">
          <span>{t('layout.preferencesPosition')}</span>
          <Select
            style={{width: 120}}
            options={[
              { label: t('layout.positions.auto'), value: 'auto' },
              { label: t('layout.positions.fixed'), value: 'fixed' },
              { label: t('layout.positions.hidden'), value: 'hidden' },
            ]}
            value={preferences.app.preferencesButtonPosition}
            onChange={(value) => setPreferences({ app: { preferencesButtonPosition: value as any } })}
          />
        </div>
      </section>

      {/* 底栏 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.footer')}</h3>
        <div className="preference-item">
          <span>{t('layout.showFooter')}</span>
          <Switch
            checked={preferences.footer.enable}
            onChange={(checked) => setPreferences({ footer: { enable: checked } })}
          />
        </div>
        <div className={`preference-item ${!preferences.footer.enable ? 'disabled' : ''}`}>
          <span>{t('layout.fixedAtBottom')}</span>
          <Switch
            disabled={!preferences.footer.enable}
            checked={preferences.footer.fixed}
            onChange={(checked) => setPreferences({ footer: { fixed: checked } })}
          />
        </div>
      </section>

      {/* 版权 */}
      <section className="layout-section">
        <h3 className="section-title">{t('layout.copyright')}</h3>
        <div className="preference-item">
          <span>{t('layout.enableCopyright')}</span>
          <Switch
            checked={preferences.copyright.enable}
            onChange={(checked) => setPreferences({ copyright: { enable: checked } })}
          />
        </div>
        <div className={`preference-item ${!preferences.copyright.enable ? 'disabled' : ''}`}>
          <span>{t('layout.companyName')}</span>
          <Input
            style={{width: 200}}
            value={preferences.copyright.companyName}
            onChange={(e) => setPreferences({ copyright: { companyName: e.target.value } })}
            disabled={!preferences.copyright.enable}
          />
        </div>
        <div className={`preference-item ${!preferences.copyright.enable ? 'disabled' : ''}`}>
          <span>{t('layout.companySite')}</span>
          <Input
            style={{width: 200}}
            value={preferences.copyright.companySiteLink}
            onChange={(e) => setPreferences({ copyright: { companySiteLink: e.target.value } })}
            disabled={!preferences.copyright.enable}
          />
        </div>
        <div className={`preference-item ${!preferences.copyright.enable ? 'disabled' : ''}`}>
          <span>{t('layout.date')}</span>
          <Input
            style={{width: 200}}
            value={preferences.copyright.date}
            onChange={(e) => setPreferences({ copyright: { date: e.target.value } })}
            disabled={!preferences.copyright.enable}
          />
        </div>
        <div className={`preference-item ${!preferences.copyright.enable ? 'disabled' : ''}`}>
          <span>{t('layout.icpNumber')}</span>
          <Input
            style={{width: 200}}
            value={preferences.copyright.icp}
            onChange={(e) => setPreferences({ copyright: { icp: e.target.value } })}
            disabled={!preferences.copyright.enable}
          />
        </div>
        <div className={`preference-item ${!preferences.copyright.enable ? 'disabled' : ''}`}>
          <span>{t('layout.icpLink')}</span>
          <Input
            style={{width: 200}}
            value={preferences.copyright.icpLink}
            onChange={(e) => setPreferences({ copyright: { icpLink: e.target.value } })}
            disabled={!preferences.copyright.enable}
          />
        </div>
      </section>
    </div>
  );
};

// frontend/admin/vue-element/src/core/preferences/components/PreferencesPanel/LayoutPanel.vue
<template>
  <div class="layout-panel">
    <!-- 布局选择 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.modes.title") }}</h3>
      <div class="layout-grid">
        <div
          v-for="option in LAYOUT_OPTIONS"
          :key="option.value"
          class="layout-wrapper"
          @click="updatePreferences({ app: { layout: option.value as any } })"
        >
          <div class="layout-item" :class="{ active: preferences.app.layout === option.value }">
            <div class="layout-preview">
              <!-- sidebar-nav -->
              <div v-if="option.value === 'sidebar-nav'" class="layout-visual sidebar-nav">
                <div class="browser-frame">
                  <div class="browser-header">
                    <div class="browser-dots">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div class="browser-body">
                    <div class="sidebar">
                      <div class="menu-item"></div>
                      <div class="menu-item"></div>
                      <div class="menu-item"></div>
                      <div class="menu-item"></div>
                      <div class="menu-item"></div>
                    </div>
                    <div class="main-content">
                      <div class="content-blocks">
                        <div class="block-row">
                          <div class="block"></div>
                          <div class="block"></div>
                        </div>
                        <div class="block-full"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- sidebar-mixed-nav -->
              <div
                v-else-if="option.value === 'sidebar-mixed-nav'"
                class="layout-visual sidebar-mixed-nav"
              >
                <div class="browser-frame">
                  <div class="browser-header">
                    <div class="browser-dots">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div class="browser-body">
                    <div class="sidebar-thin primary">
                      <div class="mini-item"></div>
                      <div class="mini-item"></div>
                      <div class="mini-item"></div>
                      <div class="mini-item"></div>
                    </div>
                    <div class="sidebar-thin gray">
                      <div class="mini-item"></div>
                      <div class="mini-item"></div>
                      <div class="mini-item"></div>
                    </div>
                    <div class="main-content">
                      <div class="content-blocks">
                        <div class="block-row">
                          <div class="block"></div>
                          <div class="block"></div>
                        </div>
                        <div class="block-full"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- header-nav -->
              <div v-else-if="option.value === 'header-nav'" class="layout-visual header-nav">
                <div class="browser-frame">
                  <div class="browser-header">
                    <div class="browser-dots">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div class="browser-body column">
                    <div class="header-nav-bar">
                      <div class="nav-item"></div>
                      <div class="nav-item"></div>
                      <div class="nav-item"></div>
                      <div class="nav-item"></div>
                      <div class="nav-item"></div>
                    </div>
                    <div class="content-blocks">
                      <div class="block-row">
                        <div class="block"></div>
                        <div class="block"></div>
                      </div>
                      <div class="block-full"></div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- mixed-nav -->
              <div v-else-if="option.value === 'mixed-nav'" class="layout-visual mixed-nav">
                <div class="browser-frame">
                  <div class="browser-header">
                    <div class="browser-dots">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div class="browser-body column">
                    <div class="header-nav-bar">
                      <div class="nav-item"></div>
                      <div class="nav-item"></div>
                      <div class="nav-item"></div>
                    </div>
                    <div class="mixed-body">
                      <div class="sidebar-thin gray">
                        <div class="mini-item"></div>
                        <div class="mini-item"></div>
                        <div class="mini-item"></div>
                      </div>
                      <div class="content-blocks">
                        <div class="block-row">
                          <div class="block"></div>
                          <div class="block"></div>
                        </div>
                        <div class="block-full"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- full-content -->
              <div v-else-if="option.value === 'full-content'" class="layout-visual full-content">
                <div class="browser-frame">
                  <div class="browser-header">
                    <div class="browser-dots">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div class="browser-body">
                    <div class="content-blocks full">
                      <div class="block-row">
                        <div class="block"></div>
                        <div class="block"></div>
                      </div>
                      <div class="block-full"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="layout-label">
            <span>{{ t(`preferences.${option.label}`) }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 内容宽度 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.contentModes.title") }}</h3>
      <div class="content-compact-grid">
        <div
          v-for="option in CONTENT_COMPACT_OPTIONS"
          :key="option.value"
          class="content-compact-wrapper"
          @click="updatePreferences({ app: { contentCompact: option.value as any } })"
        >
          <div
            class="content-compact-item"
            :class="{ active: preferences.app.contentCompact === option.value }"
          >
            <div class="content-preview">
              <div class="browser-frame-small">
                <div class="browser-header-small">
                  <div class="browser-dots-small">
                    <span></span>
                    <span></span>
                    <span></span>
                  </div>
                </div>
                <div class="browser-body-small">
                  <div
                    class="content-area-small"
                    :class="option.value === 'compact' ? 'narrow' : 'full'"
                  >
                    <div class="small-block-row">
                      <div class="small-block"></div>
                      <div class="small-block"></div>
                    </div>
                    <div class="small-block-full"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="content-label">
            <span>{{ t(`preferences.${option.label}`) }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 侧边栏 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.sidebar") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showSidebar") }}</span>
        <ElSwitch
          :model-value="preferences.sidebar.enable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ sidebar: { enable: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.collapseMenu") }}</span>
        <ElSwitch
          :model-value="preferences.sidebar.collapsed"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ sidebar: { collapsed: v as boolean } })
          "
        />
      </div>
      <div class="preference-item" :class="{ disabled: !preferences.sidebar.collapsed }">
        <span>{{ t("preferences.layout.collapseShowTitle") }}</span>
        <ElSwitch
          :disabled="!preferences.sidebar.collapsed"
          :model-value="preferences.sidebar.collapsedShowTitle"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ sidebar: { collapsedShowTitle: v as boolean } })
          "
        />
      </div>
      <div class="preference-item width-control">
        <span>{{ t("preferences.layout.width") }}</span>
        <div class="width-control-group">
          <ElButton
            size="small"
            :icon="Minus"
            :disabled="preferences.sidebar.width <= 180"
            @click="handleSidebarWidthChange(preferences.sidebar.width - 8)"
          />
          <ElInputNumber
            size="small"
            :min="180"
            :max="320"
            :model-value="preferences.sidebar.width"
            style="width: 70px"
            controls-position="right"
            @change="handleSidebarWidthChange"
          />
          <ElButton
            size="small"
            :icon="Plus"
            :disabled="preferences.sidebar.width >= 320"
            @click="handleSidebarWidthChange(preferences.sidebar.width + 8)"
          />
        </div>
      </div>
    </section>

    <!-- 顶栏 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.header") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showHeader") }}</span>
        <ElSwitch
          :model-value="preferences.header.enable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ header: { enable: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.mode") }}</span>
        <ElSegmented
          :model-value="preferences.header.mode"
          :options="headerModeOptions"
          @change="(v: string) => updatePreferences({ header: { mode: v as any } })"
        />
      </div>
    </section>

    <!-- 导航菜单 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.navigationMenu") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.menuStyle") }}</span>
        <ElSegmented
          :model-value="preferences.navigation.styleType"
          :options="menuStyleOptions"
          @change="(v: string) => updatePreferences({ navigation: { styleType: v as any } })"
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.menuSplit") }}</span>
        <ElSwitch
          :model-value="preferences.navigation.split"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ navigation: { split: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.accordionMode") }}</span>
        <ElSwitch
          :model-value="preferences.navigation.accordion"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ navigation: { accordion: v as boolean } })
          "
        />
      </div>
    </section>

    <!-- 面包屑 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.breadcrumb") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.enableBreadcrumb") }}</span>
        <ElSwitch
          :model-value="preferences.breadcrumb.enable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ breadcrumb: { enable: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.hideWhenOnlyOne") }}</span>
        <ElSwitch
          :model-value="preferences.breadcrumb.hideOnlyOne"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ breadcrumb: { hideOnlyOne: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showIcon") }}</span>
        <ElSwitch
          :model-value="preferences.breadcrumb.showIcon"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ breadcrumb: { showIcon: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showHomeButton") }}</span>
        <ElSwitch
          :model-value="preferences.breadcrumb.showHome"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ breadcrumb: { showHome: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.breadcrumbStyle") }}</span>
        <ElSegmented
          :model-value="preferences.breadcrumb.styleType"
          :options="breadcrumbStyleOptions"
          @change="(v: string) => updatePreferences({ breadcrumb: { styleType: v as any } })"
        />
      </div>
    </section>

    <!-- 标签栏 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.tabbar") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.enableTabbar") }}</span>
        <ElSwitch
          :model-value="preferences.tabbar.enable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ tabbar: { enable: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.persistTabs") }}</span>
        <ElSwitch
          :model-value="preferences.tabbar.persist"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ tabbar: { persist: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.draggableSort") }}</span>
        <ElSwitch
          :model-value="preferences.tabbar.draggable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ tabbar: { draggable: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showTabbarIcon") }}</span>
        <ElSwitch
          :model-value="preferences.tabbar.showIcon"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ tabbar: { showIcon: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showMoreButton") }}</span>
        <ElSwitch
          :model-value="preferences.tabbar.showMore"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ tabbar: { showMore: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showMaximizeButton") }}</span>
        <ElSwitch
          :model-value="preferences.tabbar.showMaximize"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ tabbar: { showMaximize: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.tabbarStyle") }}</span>
        <ElSelect
          :model-value="preferences.tabbar.styleType"
          style="width: 160px"
          @change="(v: string) => updatePreferences({ tabbar: { styleType: v as any } })"
        >
          <ElOption
            v-for="opt in tabbarStyleOptions"
            :key="opt.value"
            :label="opt.label"
            :value="opt.value"
          />
        </ElSelect>
      </div>
    </section>

    <!-- 小部件 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.widgets") }}</h3>
      <div v-for="item in widgetItems" :key="item.key" class="preference-item">
        <span>{{ t(`preferences.layout.${item.key}`) }}</span>
        <ElSwitch
          :model-value="(preferences.widget as any)[item.prop]"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ widget: { [item.prop]: v as boolean } })
          "
        />
      </div>
      <div class="preference-item">
        <span>{{ t("preferences.layout.preferencesPosition") }}</span>
        <ElSelect
          :model-value="preferences.app.preferencesButtonPosition"
          style="width: 160px"
          @change="
            (v: string) => updatePreferences({ app: { preferencesButtonPosition: v as any } })
          "
        >
          <ElOption
            v-for="opt in positionOptions"
            :key="opt.value"
            :label="opt.label"
            :value="opt.value"
          />
        </ElSelect>
      </div>
    </section>

    <!-- 底栏 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.footer") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.showFooter") }}</span>
        <ElSwitch
          :model-value="preferences.footer.enable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ footer: { enable: v as boolean } })
          "
        />
      </div>
      <div class="preference-item" :class="{ disabled: !preferences.footer.enable }">
        <span>{{ t("preferences.layout.fixedAtBottom") }}</span>
        <ElSwitch
          :disabled="!preferences.footer.enable"
          :model-value="preferences.footer.fixed"
          @change="
            (v: string | number | boolean) => updatePreferences({ footer: { fixed: v as boolean } })
          "
        />
      </div>
    </section>

    <!-- 版权 -->
    <section class="layout-section">
      <h3 class="section-title">{{ t("preferences.layout.copyright") }}</h3>
      <div class="preference-item">
        <span>{{ t("preferences.layout.enableCopyright") }}</span>
        <ElSwitch
          :model-value="preferences.copyright.enable"
          @change="
            (v: string | number | boolean) =>
              updatePreferences({ copyright: { enable: v as boolean } })
          "
        />
      </div>
      <div
        v-for="field in copyrightFields"
        :key="field.prop"
        class="preference-item"
        :class="{ disabled: !preferences.copyright.enable }"
      >
        <span>{{ t(`preferences.layout.${field.key}`) }}</span>
        <ElInput
          style="width: 200px"
          :disabled="!preferences.copyright.enable"
          :model-value="(preferences.copyright as any)[field.prop]"
          @input="(v: string) => updatePreferences({ copyright: { [field.prop]: v } })"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import {
  ElSwitch,
  ElButton,
  ElInputNumber,
  ElInput,
  ElSelect,
  ElOption,
  ElSegmented,
} from "element-plus";
import { Minus, Plus } from "@element-plus/icons-vue";
import { useI18n } from "@/i18n";
import { preferences, updatePreferences } from "../../index";

const { t } = useI18n();

const LAYOUT_OPTIONS = [
  { label: "layout.modes.sidebarNav", value: "sidebar-nav" },
  { label: "layout.modes.sidebarMixedNav", value: "sidebar-mixed-nav" },
  { label: "layout.modes.headerNav", value: "header-nav" },
  { label: "layout.modes.mixedNav", value: "mixed-nav" },
  { label: "layout.modes.fullContent", value: "full-content" },
];

const CONTENT_COMPACT_OPTIONS = [
  { label: "layout.contentModes.wide", value: "wide" },
  { label: "layout.contentModes.compact", value: "compact" },
];

const headerModeOptions = computed(() => [
  { label: t("preferences.layout.headerModes.fixed"), value: "fixed" },
  { label: t("preferences.layout.headerModes.auto"), value: "auto" },
  { label: t("preferences.layout.headerModes.static"), value: "static" },
]);

const menuStyleOptions = computed(() => [
  { label: t("preferences.layout.menuStyles.rounded"), value: "rounded" },
  { label: t("preferences.layout.menuStyles.plain"), value: "plain" },
]);

const breadcrumbStyleOptions = computed(() => [
  { label: t("preferences.layout.breadcrumbStyles.normal"), value: "normal" },
  { label: t("preferences.layout.breadcrumbStyles.background"), value: "background" },
]);

const tabbarStyleOptions = computed(() => [
  { label: t("preferences.layout.tabbarStyles.chrome"), value: "chrome" },
  { label: t("preferences.layout.tabbarStyles.card"), value: "card" },
  { label: t("preferences.layout.tabbarStyles.brisk"), value: "brisk" },
  { label: t("preferences.layout.tabbarStyles.plain"), value: "plain" },
]);

const positionOptions = computed(() => [
  { label: t("preferences.layout.positions.auto"), value: "auto" },
  { label: t("preferences.layout.positions.fixed"), value: "fixed" },
  { label: t("preferences.layout.positions.hidden"), value: "hidden" },
]);

const widgetItems = [
  { key: "globalSearch", prop: "globalSearch" },
  { key: "themeToggle", prop: "themeToggle" },
  { key: "languageToggle", prop: "languageToggle" },
  { key: "fullscreen", prop: "fullscreen" },
  { key: "notification", prop: "notification" },
  { key: "lockScreen", prop: "lockScreen" },
  { key: "sidebarToggle", prop: "sidebarToggle" },
  { key: "refresh", prop: "refresh" },
];

const copyrightFields = [
  { key: "companyName", prop: "companyName" },
  { key: "companySite", prop: "companySiteLink" },
  { key: "date", prop: "date" },
  { key: "icpNumber", prop: "icp" },
  { key: "icpLink", prop: "icpLink" },
];

function handleSidebarWidthChange(width: number | null | undefined) {
  if (width && width >= 180 && width <= 320) {
    updatePreferences({ sidebar: { width } });
  }
}
</script>

<style src="./LayoutPanel.scss" scoped lang="scss"></style>
