// frontend/admin/vue-element/src/pages/app/tenant/tenant/tenant-drawer.vue
<template>
  <ProModal
    v-model:visible="visible"
    :title="title"
    :config="{ component: 'drawer', drawer: { size: DRAWER_WIDTH, closeOnClickModal: false } }"
  >
    <ElForm ref="formRef" :model="formData" :rules="formRules" label-width="120px">
      <!-- 基本信息 -->
      <ElFormItem :label="$t('pages.tenant.name')" prop="name" required>
        <ElInput v-model="formData.name" :placeholder="$t('common.placeholder.input')" clearable />
      </ElFormItem>

      <ElFormItem :label="$t('pages.tenant.code')" prop="code" required>
        <ElInput v-model="formData.code" :placeholder="$t('common.placeholder.input')" clearable />
      </ElFormItem>

      <ElFormItem :label="$t('pages.tenant.type')" prop="type" required>
        <ElSelect
          v-model="formData.type"
          :placeholder="$t('common.placeholder.select')"
          filterable
          class="w-full"
        >
          <ElOption
            v-for="item in tenantTypeList"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
        </ElSelect>
      </ElFormItem>

      <ElFormItem :label="$t('pages.tenant.auditStatus')" prop="auditStatus" required>
        <ElSelect
          v-model="formData.auditStatus"
          :placeholder="$t('common.placeholder.select')"
          filterable
          class="w-full"
        >
          <ElOption
            v-for="item in tenantAuditStatusList"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
        </ElSelect>
      </ElFormItem>

      <ElFormItem :label="$t('common.table.status')" prop="status" required>
        <ElSelect
          v-model="formData.status"
          :placeholder="$t('common.placeholder.select')"
          filterable
          class="w-full"
        >
          <ElOption
            v-for="item in tenantStatusList"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
        </ElSelect>
      </ElFormItem>

      <ElFormItem :label="$t('common.table.remark')">
        <ElInput
          v-model="formData.remark"
          type="textarea"
          :rows="3"
          :placeholder="$t('common.placeholder.input')"
        />
      </ElFormItem>

      <ElFormItem :label="$t('pages.tenant.subscriptionPlan')" prop="subscriptionPlan">
        <ElSelect
          v-model="formData.subscriptionPlan"
          :placeholder="$t('common.placeholder.select')"
          filterable
          clearable
          class="w-full"
        >
          <ElOption
            v-for="item in planOptions"
            :key="item.id"
            :label="item.name"
            :value="item.id as number"
          />
        </ElSelect>
      </ElFormItem>

      <ElFormItem :label="$t('pages.tenant.expiredAt')" prop="expiredAt">
        <ElDatePicker
          v-model="formData.expiredAt"
          type="datetime"
          :placeholder="$t('common.placeholder.select')"
          class="w-full"
        />
      </ElFormItem>

      <!-- 编辑模式下显示用量与配额 + 清理数据按钮 -->
      <template v-if="!isCreate && usageData">
        <ElDivider>{{ $t("pages.tenant.usageSection") }}</ElDivider>
        <ElDescriptions :column="1" size="small" border>
          <ElDescriptionsItem :label="$t('pages.tenant.usageUserCount')">
            {{ usageData.userCount ?? 0 }}
          </ElDescriptionsItem>
          <ElDescriptionsItem :label="$t('pages.tenant.usageStorage')">
            {{ usageData.storageUsedBytes ?? 0 }} bytes
          </ElDescriptionsItem>
          <ElDescriptionsItem :label="$t('pages.tenant.usageApiCalls')">
            {{ usageData.apiCallCount ?? 0 }}
          </ElDescriptionsItem>
          <ElDescriptionsItem :label="$t('pages.tenant.usagePlan')">
            {{ usageData.planName ?? $t("pages.tenant.usageNoPlan") }}
          </ElDescriptionsItem>
        </ElDescriptions>
        <div v-if="usageData.quotas && usageData.quotas.length" style="margin-top: 16px">
          <div v-for="(q, idx) in usageData.quotas" :key="idx" style="margin-bottom: 12px">
            <div style="margin-bottom: 4px">
              {{ getQuotaLabel(q.quotaType) }}: {{ getQuotaCurrent(q.quotaType) }} /
              {{ q.quotaValue ?? 0 }}
            </div>
            <ElProgress
              :percentage="getQuotaPercent(q.quotaType, q.quotaValue ?? 0)"
              :stroke-width="6"
            />
          </div>
        </div>
        <div style="margin-top: 24px">
          <ElPopconfirm
            :title="$t('pages.tenant.cleanupConfirmTitle')"
            :content="$t('pages.tenant.cleanupConfirmDesc')"
            confirm-button-type="danger"
            @confirm="handleCleanup"
          >
            <template #reference>
              <ElButton type="danger" :loading="cleanupLoading">
                {{ $t("pages.tenant.cleanupData") }}
              </ElButton>
            </template>
          </ElPopconfirm>
        </div>
      </template>

      <!-- 管理员设置（仅创建时显示） -->
      <ElDivider v-if="isCreate">{{ $t("pages.tenant.adminSetting") }}</ElDivider>

      <ElFormItem
        v-if="isCreate"
        :label="$t('pages.tenant.adminUserName')"
        prop="user.username"
        required
      >
        <ElInput
          v-model="formData.user.username"
          :placeholder="$t('common.placeholder.input')"
          clearable
        />
      </ElFormItem>

      <ElFormItem
        v-if="isCreate"
        :label="$t('pages.tenant.adminPassword')"
        prop="password"
        required
      >
        <ElInput
          v-model="formData.password"
          type="password"
          show-password
          :placeholder="$t('common.placeholder.input')"
        />
      </ElFormItem>

      <ElFormItem
        v-if="isCreate"
        :label="$t('pages.tenant.adminPasswordConfirm')"
        prop="passwordConfirm"
        required
      >
        <ElInput
          v-model="formData.passwordConfirm"
          type="password"
          show-password
          :placeholder="$t('common.placeholder.input')"
        />
      </ElFormItem>

      <ElFormItem
        v-if="isCreate"
        :label="$t('pages.tenant.adminMobile')"
        prop="user.mobile"
        required
      >
        <ElInput
          v-model="formData.user.mobile"
          :placeholder="$t('common.placeholder.input')"
          clearable
        />
      </ElFormItem>

      <ElFormItem v-if="isCreate" :label="$t('pages.tenant.adminEmail')" prop="user.email" required>
        <ElInput
          v-model="formData.user.email"
          :placeholder="$t('common.placeholder.input')"
          clearable
        />
      </ElFormItem>
    </ElForm>

    <template #footer>
      <div class="drawer-footer">
        <ElButton @click="handleClose">{{ $t("common.button.cancel") }}</ElButton>
        <ElButton type="primary" :loading="loading" @click="handleSubmit">
          {{ $t("common.button.confirm") }}
        </ElButton>
      </div>
    </template>
  </ProModal>
</template>

<script lang="ts" setup>
import { computed, ref, watch } from "vue";

import { ElMessage } from "element-plus";
import type { FormInstance, FormRules } from "element-plus";
import dayjs from "dayjs";

import {
  tenantAuditStatusList,
  tenantStatusList,
  tenantTypeList,
  useCreateTenantWithAdminUser,
  useUpdateTenant,
  useUserExists,
  fetchTenantUsage,
  useCleanupTenantData,
  fetchListTenants,
  fetchListPlans,
} from "@/api/composables";
import { PaginationQuery } from "@/core/transport/rest";
import type { identityservicev1_Plan as Plan } from "@/api/generated/admin/service/v1";
import type { identityservicev1_Tenant as Tenant } from "@/api/generated/admin/service/v1";
import { $t } from "@/core/i18n";
import { DRAWER_WIDTH } from "@/constants";
import { injectProModalApi } from "@/components/Pro";
import ProModal from "@/components/Pro/ProModal/index.vue";

// 通过 inject 获取列表页传入的 modalApi
const modalApi = injectProModalApi();

// 将日期组件的值（Date/字符串等）归一化为 protobuf Timestamp 可解析的 RFC3339 字符串。
// 后端 protojson 要求 Timestamp 必须是 RFC3339，直接传 "2026-09-30 00:00:00" 等形式会报 CODEC。
function toProtoTimestamp(v?: Date | string | number | null): string | undefined {
  if (!v) return undefined;
  const d = dayjs(v);
  return d.isValid() ? d.toISOString() : String(v);
}

// 注意：不能使用 modalApi.getData()，其内部对 toRaw(store).sharedData 取值会丢失响应式，
// 导致多次 open（新增↔编辑切换、编辑不同租户）时 data/isCreate 停留在首次快照，造成串数据。
// 这里直接读取响应式的 store.sharedData。
const data = computed(() => modalApi.store.sharedData as { create?: boolean; row?: Tenant });
const isCreate = computed(() => !!data.value.create);

const visible = computed({
  get: () => modalApi.store.isOpen,
  set: (v) => {
    if (!v) modalApi.close();
  },
});

const { mutateAsync: createTenantWithAdminUserMut } = useCreateTenantWithAdminUser();
const { mutateAsync: updateTenantMut } = useUpdateTenant();
const { mutateAsync: userExists } = useUserExists();

// 编辑模式下按需加载租户用量数据（usageData）。
// 不在 setup 顶层发起请求：仅当抽屉打开且选中真实租户行时，用 fetchTenantUsage 命令式拉取，
// 避免 row.id 为空时以 id=0 发请求触发 400。与 vue-vben 实现保持一致。
const usageData = ref<any>(null);
const cleanupLoading = ref(false);
const { mutateAsync: cleanupMut } = useCleanupTenantData();

// 辅助函数：根据配额类型返回标签/当前值/百分比。

function getQuotaLabel(qt: any): string {
  if (qt === 1) return $t("pages.tenant.usageUserCount");
  if (qt === 2) return $t("pages.tenant.usageStorage");
  if (qt === 3) return $t("pages.tenant.usageApiCalls");
  return $t("pages.tenant.quotaType");
}
function getQuotaCurrent(qt: any): number {
  const ud = usageData.value as any;
  if (!ud) return 0;
  if (qt === 1) return ud.userCount ?? 0;
  if (qt === 2) return ud.storageUsedBytes ?? 0;
  if (qt === 3) return ud.apiCallCount ?? 0;
  return 0;
}
function getQuotaPercent(qt: any, limit: number): number {
  const current = getQuotaCurrent(qt);
  if (limit <= 0) return 0;
  return Math.min(100, (current / limit) * 100);
}

async function handleCleanup() {
  if (!data.value.row?.id) return;
  try {
    cleanupLoading.value = true;
    await cleanupMut({ id: data.value.row.id });
    ElMessage.success($t("pages.tenant.cleanupSuccess"));
    modalApi.close();
  } catch (err: any) {
    ElMessage.error(err?.message || $t("pages.tenant.cleanupFailed"));
  } finally {
    cleanupLoading.value = false;
  }
}

// 加载状态
const loading = ref(false);

// 套餐下拉选项（订阅套餐）
const planOptions = ref<(Plan & { id?: number; name?: string })[]>([]);

// 表单数据
const formData = ref({
  name: "",
  code: "",
  type: "PAID",
  auditStatus: "APPROVED",
  status: "ON",
  remark: "",
  subscriptionPlan: undefined as number | undefined,
  expiredAt: "" as string,
  user: {
    username: "",
    mobile: "",
    email: "",
  },
  password: "",
  passwordConfirm: "",
});

const formRef = ref<FormInstance>();

// 表单校验规则（补齐 required + 格式校验，与 React 版对齐）
const formRules: FormRules = {
  name: [{ required: true, message: $t("common.validation.required"), trigger: "blur" }],
  code: [{ required: true, message: $t("common.validation.required"), trigger: "blur" }],
  type: [{ required: true, message: $t("common.validation.selectRequired"), trigger: "change" }],
  auditStatus: [
    { required: true, message: $t("common.validation.selectRequired"), trigger: "change" },
  ],
  status: [{ required: true, message: $t("common.validation.selectRequired"), trigger: "change" }],
  "user.username": [{ required: true, message: $t("common.validation.required"), trigger: "blur" }],
  "user.mobile": [
    { required: true, message: $t("common.validation.required"), trigger: "blur" },
    {
      pattern: /^1[3-9]\d{9}$/,
      message: $t("common.validation.phoneFormat"),
      trigger: "blur",
    },
  ],
  "user.email": [
    { required: true, message: $t("common.validation.required"), trigger: "blur" },
    { type: "email", message: $t("common.validation.email"), trigger: "blur" },
  ],
  password: [
    { required: true, message: $t("common.validation.required"), trigger: "blur" },
    {
      // 与后端等保口令策略一致：≥8 位，小写/大写/数字/符号四类取三。
      validator: (_rule, value, callback) => {
        if (!value) return callback();
        const pwd = String(value);
        if (pwd.length < 8) return callback(new Error($t("page.tenant.passwordComplexity")));
        let classes = 0;
        if (/[a-z]/.test(pwd)) classes++;
        if (/[A-Z]/.test(pwd)) classes++;
        if (/\d/.test(pwd)) classes++;
        if (/[^A-Za-z0-9]/.test(pwd)) classes++;
        if (classes < 3) return callback(new Error($t("page.tenant.passwordComplexity")));
        return callback();
      },
      trigger: "blur",
    },
  ],
  passwordConfirm: [
    { required: true, message: $t("common.validation.required"), trigger: "blur" },
    { min: 6, message: $t("common.validation.passwordMin"), trigger: "blur" },
  ],
};

// 弹窗标题
const title = computed(() =>
  isCreate.value
    ? $t("common.modal.create", { moduleName: $t("pages.tenant.moduleName") })
    : $t("common.modal.update", { moduleName: $t("pages.tenant.moduleName") })
);

// 监听弹窗打开/关闭
watch(visible, async (val) => {
  if (val) {
    if (!isCreate.value && data.value.row) {
      // 编辑模式
      const row = data.value.row;
      formData.value = {
        name: row.name || "",
        code: row.code || "",
        type: row.type || "PAID",
        auditStatus: row.auditStatus || "APPROVED",
        status: row.status || "ON",
        remark: row.remark || "",
        subscriptionPlan: row.planId,
        expiredAt: "",
        user: {
          username: "",
          mobile: "",
          email: "",
        },
        password: "",
        passwordConfirm: "",
      };

      // 加载该租户的用量与配额对比数据
      // 仅当存在真实租户 ID 时按需拉取，避免 id=0 触发 400
      const rowId = data.value.row?.id;
      if (rowId) {
        try {
          const res = await fetchTenantUsage({ id: rowId });
          usageData.value = res ?? null;
        } catch {
          usageData.value = null;
        }
      } else {
        usageData.value = null;
      }
    } else {
      // 创建模式
      resetForm();
      usageData.value = null;
    }

    // 加载套餐下拉选项（订阅套餐）
    try {
      const res = await fetchListPlans(new PaginationQuery({ paging: { page: 1, pageSize: 100 } }));
      planOptions.value = (res.items || []) as (Plan & { id?: number; name?: string })[];
    } catch (err) {
      console.error("Failed to load plan options:", err);
      planOptions.value = [];
    }
  } else {
    // ProModal 关闭时自动重置表单
    resetForm();
  }
});

// 重置表单
const resetForm = () => {
  formData.value = {
    name: "",
    code: "",
    type: "PAID",
    auditStatus: "APPROVED",
    status: "ON",
    remark: "",
    subscriptionPlan: undefined,
    expiredAt: "",
    user: {
      username: "",
      mobile: "",
      email: "",
    },
    password: "",
    passwordConfirm: "",
  };
};

// 关闭弹窗
const handleClose = () => {
  modalApi.close();
  resetForm();
};

// 提交表单
const handleSubmit = async () => {
  try {
    loading.value = true;

    // 表单校验（required + 手机/邮箱格式 + 密码长度，由 formRules 驱动）
    if (!formRef.value) return;
    await formRef.value.validate();

    if (isCreate.value) {
      await createTenantWithAdminUser();
    } else {
      await updateTenant();
    }

    // 成功回调
    modalApi.close();
  } catch (error: any) {
    console.error("Submit error:", error);
    // 透传后端可读错误（如密码复杂度不达标）。表单校验失败会被 Element 组装成对象、
    // 无 string message，此处不会误弹（校验错误由表单内联展示）。
    if (error?.message && typeof error.message === "string") {
      ElMessage.error(error.message);
    }
  } finally {
    loading.value = false;
  }
};

// 创建租户和管理员用户
async function createTenantWithAdminUser() {
  // 检查密码和确认密码是否一致
  if (formData.value.password !== formData.value.passwordConfirm) {
    ElMessage.error($t("pages.notification.password_mismatch"));
    return;
  }

  // 检查租户编码是否存在
  try {
    const result = await fetchListTenants(
      new PaginationQuery({ formValues: { code: formData.value.code } })
    );
    if (result.items && result.items.length > 0) {
      // 查询成功且存在重复，提示编码已存在
      ElMessage.error($t("pages.tenant.tenant_code_exists"));
      return;
    }
  } catch {
    // 查询本身失败（网络/500 等），不能误判为编码已存在
    ElMessage.error($t("common.operationFailed"));
    return;
  }

  // 检查用户名是否存在
  try {
    await userExists({ username: formData.value.user.username });
  } catch {
    ElMessage.error($t("pages.tenant.notification.user_username_exists"));
    return;
  }

  await createTenantWithAdminUserMut({
    tenant: {
      name: formData.value.name,
      code: formData.value.code,
      type: formData.value.type as any,
      auditStatus: formData.value.auditStatus as any,
      status: formData.value.status as any,
      planId: formData.value.subscriptionPlan,
      expiredAt: toProtoTimestamp(formData.value.expiredAt),
      remark: formData.value.remark,
    },
    user: formData.value.user as any,
    password: formData.value.password,
  });

  ElMessage.success($t("common.notification.create_success"));
}

// 更新租户
async function updateTenant() {
  if (!data.value.row?.id) {
    ElMessage.error($t("common.notification.update_failed"));
    return;
  }

  await updateTenantMut({
    id: data.value.row!.id,
    values: {
      name: formData.value.name,
      code: formData.value.code,
      type: formData.value.type,
      auditStatus: formData.value.auditStatus,
      status: formData.value.status,
      remark: formData.value.remark,
      planId: formData.value.subscriptionPlan,
      expiredAt: toProtoTimestamp(formData.value.expiredAt),
    },
  });

  ElMessage.success($t("common.notification.update_success"));
}
</script>

<style scoped>
.drawer-footer {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
}
</style>

// frontend/admin/react/src/pages/app/tenant/tenant/components/TenantDrawer.tsx
import React, { useEffect, useRef, useState } from 'react';
import { DrawerForm, ProFormText, ProFormSelect, ProFormTextArea, ProFormDateTimePicker } from '@ant-design/pro-components';
import type { ProFormInstance } from '@ant-design/pro-components';
import { Button, message, Divider, Popconfirm, Descriptions, Tag, Progress } from 'antd';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import dayjs from 'dayjs';
import { useUpdateTenant, useCreateTenantWithAdminUser, useGetTenantUsage, useCleanupTenantData } from '@/api/hooks/tenant';
import { fetchListPlans } from '@/api/hooks/plan';
import { PaginationQuery } from '@/core';
import type {
  identityservicev1_Tenant,
  identityservicev1_Tenant_Type,
  identityservicev1_Tenant_Status,
  identityservicev1_Tenant_AuditStatus,
} from '@/api/generated/admin/service/v1';
import {
  getTenantTypeOptions,
  getAuditStatusOptions,
  getTenantStatusOptions,
  SELECT_FILTER_PROPS,
} from '../constants';

interface TenantDrawerProps {
  open: boolean;
  mode: 'create' | 'edit';
  data?: identityservicev1_Tenant;
  onClose: () => void;
  onSuccess: () => void;
}

/**
 * 将日期选择器返回的本地时间（如 "2026-09-30 00:00:00"）归一化为
 * protobuf google.protobuf.Timestamp 可解析的 RFC3339 字符串。
 * 后端 protojson 要求 Timestamp 必须是 RFC3339，直接传 "2026-09-30 00:00:00" 会报 CODEC 错误。
 */
const toProtoTimestamp = (v?: any): string | undefined => {
  if (!v) return undefined;
  const d = dayjs(v);
  return d.isValid() ? d.toISOString() : String(v);
};

/**
 * 租户编辑/创建 Drawer 组件（基于 DrawerForm）
 */
const TenantDrawer: React.FC<TenantDrawerProps> = ({
  open,
  mode,
  data,
  onClose,
  onSuccess,
}) => {
  const { t } = useTranslation('tenant');
  const queryClient = useQueryClient();
  const formRef = useRef<ProFormInstance>(null);

  const updateMutation = useUpdateTenant();
  const createMutation = useCreateTenantWithAdminUser();

  // 编辑模式下加载租户用量与配额对比数据。
  const usageQuery = useGetTenantUsage(
    { id: data?.id ?? 0 },
    { enabled: open && mode === 'edit' && !!data?.id },
  );
  const cleanupMutation = useCleanupTenantData();

  // 套餐下拉数据
  const [planOptions, setPlanOptions] = useState<{ label: string; value: number }[]>([]);

  // 打开抽屉时加载套餐目录下拉
  useEffect(() => {
    if (open) {
      fetchListPlans(new PaginationQuery({ formValues: {} }))
        .then((res) => {
          const options = (res.items || []).map((item: any) => ({
            label: item.name,
            value: item.id,
          }));
          setPlanOptions(options);
        })
        .catch(() => setPlanOptions([]));
    }
  }, [open]);

  // 当 Drawer 打开时，设置表单初始值
  useEffect(() => {
    if (open) {
      setTimeout(() => {
        if (mode === 'edit' && data && formRef.current) {
          formRef.current.setFieldsValue({
            name: data.name,
            code: data.code,
            tenantType: data.type,
            auditStatus: data.auditStatus,
            status: data.status,
            planId: data.planId,
            expiredAt: data.expiredAt,
            remark: data.remark,
          });
        } else if (formRef.current) {
          // 创建模式下的默认值
          formRef.current.setFieldsValue({
            tenantType: 'PAID',
            auditStatus: 'APPROVED',
            status: 'ON',
          });
        }
      }, 0);
    }
  }, [open, mode, data]);

  // 提交处理
  const handleSubmit = async (values: any) => {
    try {
      if (mode === 'create') {
        // 检查密码和确认密码是否一致
        if (values.password !== values.passwordConfirm) {
          message.error(t('passwordMismatch'));
          return false;
        }

        // 创建租户及管理员用户
        await createMutation.mutateAsync({
          tenant: {
            name: values.name,
            code: values.code,
            type: values.tenantType as identityservicev1_Tenant_Type,
            auditStatus: values.auditStatus as identityservicev1_Tenant_AuditStatus,
            status: values.status as identityservicev1_Tenant_Status,
            planId: values.planId,
            expiredAt: toProtoTimestamp(values.expiredAt),
            remark: values.remark,
          },
          user: {
            username: values.username,
            mobile: values.mobile,
            email: values.email,
            orgUnitIds: undefined,
            orgUnitNames: undefined,
            positionIds: undefined,
            positionNames: undefined,
            roleIds: undefined,
            roles: undefined,
            roleNames: undefined,
          },
          password: values.password,
        });
        message.success(t('createSuccess'));
      } else {
        // 更新租户
        if (!data?.id) {
          message.error(t('tenantIdMissing'));
          return false;
        }
        await updateMutation.mutateAsync({
          id: data.id,
          values: {
            name: values.name,
            code: values.code,
            type: values.tenantType as identityservicev1_Tenant_Type,
            auditStatus: values.auditStatus as identityservicev1_Tenant_AuditStatus,
            status: values.status as identityservicev1_Tenant_Status,
            planId: values.planId,
            expiredAt: toProtoTimestamp(values.expiredAt),
            remark: values.remark,
          },
        });
        message.success(t('updateSuccess'));
      }

      // 刷新列表
      queryClient.invalidateQueries({ queryKey: ['listTenants'] });

      // 重置表单并关闭
      formRef.current?.resetFields();
      onSuccess();

      return true;
    } catch (error: any) {
      message.error(error.message || (mode === 'create' ? t('createFailed') : t('updateFailed')));
      return false;
    }
  };

  return (
    <DrawerForm
      formRef={formRef}
      title={mode === 'create' ? t('create') : t('edit')}
      open={open}
      onOpenChange={(visible) => {
        if (!visible) {
          formRef.current?.resetFields();
          onClose();
        }
      }}
      initialValues={{
        tenantType: 'PAID',
        auditStatus: 'APPROVED',
        status: 'ON',
      }}
      onFinish={handleSubmit}
      submitter={{
        render: (_, dom) => [
          <Button key="reset" onClick={() => formRef.current?.resetFields()}>
            {t('reset')}
          </Button>,
          ...dom,
        ],
      }}
      drawerProps={{
        destroyOnClose: true,
        onClose,
        size: 600,
      }}
    >
      <ProFormText
        name="name"
        label={t('name')}
        placeholder={t('namePlaceholder')}
        rules={[
          { required: true, message: t('requiredName') },
          { max: 50, message: t('maxChars', { max: 50 }) },
        ]}
        fieldProps={{
          allowClear: true,
        }}
      />

      <ProFormText
        name="code"
        label={t('code')}
        placeholder={t('codePlaceholder')}
        rules={[
          { required: true, message: t('requiredCode') },
          { max: 50, message: t('maxChars', { max: 50 }) },
        ]}
        fieldProps={{
          allowClear: true,
        }}
      />

      <ProFormSelect
        name="tenantType"
        label={t('tenantType')}
        placeholder={t('tenantTypePlaceholder')}
        options={getTenantTypeOptions(t)}
        rules={[{ required: true, message: t('requiredType') }]}
        fieldProps={SELECT_FILTER_PROPS}
      />

      <ProFormSelect
        name="auditStatus"
        label={t('auditStatus')}
        placeholder={t('auditStatusPlaceholder')}
        options={getAuditStatusOptions(t)}
        rules={[{ required: true, message: t('requiredAuditStatus') }]}
        fieldProps={SELECT_FILTER_PROPS}
      />

      <ProFormSelect
        name="status"
        label={t('status')}
        placeholder={t('statusPlaceholder')}
        options={getTenantStatusOptions(t)}
        rules={[{ required: true, message: t('requiredStatus') }]}
        fieldProps={SELECT_FILTER_PROPS}
      />

      <ProFormSelect
        name="planId"
        label={t('subscriptionPlan')}
        placeholder={t('subscriptionPlanPlaceholder')}
        options={planOptions}
        fieldProps={SELECT_FILTER_PROPS}
      />

      <ProFormDateTimePicker
        name="expiredAt"
        label={t('expiredAt')}
        placeholder={t('expiredAtPlaceholder')}
        fieldProps={{ allowClear: true, showTime: true, style: { width: '100%' } }}
      />

      <ProFormTextArea
        name="remark"
        label={t('remark')}
        placeholder={t('remarkPlaceholder')}
        fieldProps={{
          rows: 4,
          allowClear: true,
          maxLength: 500,
          showCount: true,
        }}
      />

      {/* 编辑模式下显示用量与配额对比 + 清理数据按钮 */}
      {mode === 'edit' && usageQuery.data && (
        <>
          <Divider style={{ margin: '24px 0 16px' }}>{t('usageSection')}</Divider>
          <Descriptions column={1} size="small" bordered>
            <Descriptions.Item label={t('usageUserCount')}>
              {usageQuery.data.userCount ?? 0}
            </Descriptions.Item>
            <Descriptions.Item label={t('usageStorage')}>
              {usageQuery.data.storageUsedBytes ?? 0} bytes
            </Descriptions.Item>
            <Descriptions.Item label={t('usageApiCalls')}>
              {usageQuery.data.apiCallCount ?? 0}
            </Descriptions.Item>
            <Descriptions.Item label={t('usagePlan')}>
              {usageQuery.data.planName ?? t('usageNoPlan')}
            </Descriptions.Item>
          </Descriptions>
          {usageQuery.data.quotas && usageQuery.data.quotas.length > 0 && (
            <div style={{ marginTop: 16 }}>
              {usageQuery.data.quotas.map((q, idx) => {
                let label = q.quotaType?.toString() ?? '';
                let current = 0;
                let limit = q.quotaValue ?? 0;
                if (q.quotaType === 1) {
                  label = t('usageUserCount');
                  current = usageQuery.data.userCount ?? 0;
                } else if (q.quotaType === 2) {
                  label = t('usageStorage');
                  current = usageQuery.data.storageUsedBytes ?? 0;
                } else if (q.quotaType === 3) {
                  label = t('usageApiCalls');
                  current = usageQuery.data.apiCallCount ?? 0;
                }
                const pct = limit > 0 ? Math.min(100, (current / limit) * 100) : 0;
                return (
                  <div key={idx} style={{ marginBottom: 12 }}>
                    <div style={{ marginBottom: 4 }}>
                      {label}: {current} / {limit}
                    </div>
                    <Progress percent={pct} size="small" />
                  </div>
                );
              })}
            </div>
          )}
          <div style={{ marginTop: 24 }}>
            <Popconfirm
              title={t('cleanupConfirmTitle')}
              description={t('cleanupConfirmDesc')}
              okText={t('common:button.confirm')}
              okButtonProps={{ danger: true }}
              cancelText={t('common:button.cancel')}
              onConfirm={async () => {
                try {
                  await cleanupMutation.mutateAsync({ id: data?.id ?? 0 });
                  message.success(t('cleanupSuccess'));
                  queryClient.invalidateQueries({ queryKey: ['listTenants'] });
                  onClose();
                } catch (err: any) {
                  message.error(err?.message || t('cleanupFailed'));
                }
              }}
            >
              <Button danger loading={cleanupMutation.isPending}>
                {t('cleanupData')}
              </Button>
            </Popconfirm>
          </div>
        </>
      )}

      {/* 创建模式下显示管理员账号配置 */}
      {mode === 'create' && (
        <>
          <Divider style={{ margin: '24px 0 16px' }}>{t('adminSection')}</Divider>

          <ProFormText
            name="username"
            label={t('adminUsernameLabel')}
            placeholder={t('adminUsernamePlaceholder')}
            rules={[
              { required: true, message: t('requiredAdminUsername') },
              { max: 50, message: t('maxChars', { max: 50 }) },
            ]}
            fieldProps={{
              allowClear: true,
            }}
          />

          <ProFormText.Password
            name="password"
            label={t('password')}
            placeholder={t('passwordPlaceholder')}
            rules={[
              { required: true, message: t('requiredPassword') },
              {
                validator: async (_, value) => {
                  if (!value) return Promise.resolve();
                  // 与后端等保口令策略一致：≥8 位，小写/大写/数字/符号四类取三。
                  const errMsg = t('passwordComplexity');
                  if (typeof value !== 'string' || value.length < 8) {
                    return Promise.reject(new Error(errMsg));
                  }
                  let classes = 0;
                  if (/[a-z]/.test(value)) classes++;
                  if (/[A-Z]/.test(value)) classes++;
                  if (/\d/.test(value)) classes++;
                  if (/[^A-Za-z0-9]/.test(value)) classes++;
                  if (classes < 3) return Promise.reject(new Error(errMsg));
                  return Promise.resolve();
                },
              },
            ]}
            fieldProps={{
              allowClear: true,
            }}
          />

          <ProFormText.Password
            name="passwordConfirm"
            label={t('passwordConfirm')}
            placeholder={t('passwordConfirmPlaceholder')}
            rules={[
              { required: true, message: t('requiredPasswordConfirm') },
              { min: 6, message: t('passwordMin', { min: 6 }) },
              {
                validator: async (_, value) => {
                  const password = formRef.current?.getFieldValue('password');
                  if (value && password !== value) {
                    return Promise.reject(new Error(t('passwordMismatch')));
                  }
                  return Promise.resolve();
                },
              },
            ]}
            fieldProps={{
              allowClear: true,
            }}
          />

          <ProFormText
            name="mobile"
            label={t('mobile')}
            placeholder={t('mobilePlaceholder')}
            rules={[
              { required: true, message: t('requiredMobile') },
              { pattern: /^1[3-9]\d{9}$/, message: t('mobileInvalid') },
            ]}
            fieldProps={{
              allowClear: true,
            }}
          />

          <ProFormText
            name="email"
            label={t('email')}
            placeholder={t('emailPlaceholder')}
            rules={[
              { required: true, message: t('requiredEmail') },
              { type: 'email', message: t('emailInvalid') },
            ]}
            fieldProps={{
              allowClear: true,
            }}
          />
        </>
      )}
    </DrawerForm>
  );
};

export default TenantDrawer;
